local theme = {
	id = "base",
	name = "Text only",
	base_id = nil,

	folder = "base",
	frames = {
		subfolder = nil,
		default = "frame.png",
		on = "frame_on.png",
		off = "frame_off.png",
	},
	backgrounds = {
		subfolder = nil,
		default = "background.png",
		-- virtualconsole = "",
		-- main = "",
	},
	text_icons_off = {
		subfolder = nil,
		default = "empty.png",
		-- ["Toggle screens"] = "",
		-- ["Toggle door"] = "",
		-- ["Toggle lock"] = "",
		-- ["Toggle power"] = "",
		-- ["Self-repair"] = "",
		-- ["Redecoration"] = "",
		-- ["Vortex Flight"] = "",
		-- ["Throttle"] = "",
		-- ["Fast Return"] = "",
		-- ["Flightmode"] = "",
		-- ["Anti-Gravs"] = "",
		-- ["Physlock"] = "",
		-- ["H.A.D.S."] = "",
		-- ["Destination"] = "",
		-- ["Flight Control"] = "",
		-- ["Virtual Console"] = "",
		-- ["Coordinates"] = "",
		-- ["Music"] = "",
		-- ["Scanner"] = "",
		-- ["Settings"] = "",
		-- ["menu"] = "",
		-- ["back"] = "",
		-- ["<<<"] = "",
		-- [">>>"] = "",
		-- ["exit"] = "",
		-- ["popup"] = "",
	},
	text_icons_on = {
		subfolder = nil,
		default = "empty.png",
		-- ["Toggle screens"] = "",
		-- ["Toggle door"] = "",
		-- ["Toggle lock"] = "",
		-- ["Toggle power"] = "",
		-- ["Self-repair"] = "",
		-- ["Redecoration"] = "",
		-- ["Vortex Flight"] = "",
		-- ["Throttle"] = "",
		-- ["Fast Return"] = "",
		-- ["Flightmode"] = "",
		-- ["Anti-Gravs"] = "",
		-- ["Physlock"] = "",
		-- ["H.A.D.S."] = "",
		-- ["Destination"] = "",
		-- ["Flight Control"] = "",
		-- ["Virtual Console"] = "",
		-- ["Coordinate"] = "",
		-- ["Music"] = "",
		-- ["Scanner"] = "",
		-- ["Settings"] = "",
		-- ["menu"] = "",
		-- ["back"] = "",
		-- ["<<<"] = "",
		-- [">>>"] = "",
		-- ["exit"] = "",
		-- ["popup"] = "",
	},
}

TARDIS:AddGUITheme(theme)