local theme = {
	id = "default-transparent",
	name = "Transparent",
	base_id = "default",

	folder = "default-transparent",
	frames = {
		subfolder = "frames",
		default = "tblue.png",
		on = "tgreen.png",
		off = "tred.png",
	},
	backgrounds = {},
	text_icons_off = {
		subfolder = "off",
		default = "empty.png",
		["Toggle screens"] = "control_screens.png",
		["Toggle door"] = "control_door.png",
		["Toggle power"] = "control_power.png",
		["Redecoration"] = "control_redecoration.png",
		["Throttle"] = "control_throttle.png",
		["Fast Return"] = "control_fastreturn.png",
		["Flightmode"] = "control_flight.png",
		["H.A.D.S."] = "control_hads.png",
		["Destination"] = "screen_destination.png",
		["Flight Control"] = "screen_thirdperson.png",
		["Coordinates"] = "screen_coords.png",
		["Music"] = "screen_music.png",
		["Scanner"] = "screen_scanner.png",
		["Settings"] = "screen_settings.png",
		["TARDIS Status"] = "screen_status.png",
	},
	text_icons_on = {
		subfolder = "on",
		default = "empty.png",
		["Toggle screens"] = "control_screens.png",
		["Toggle door"] = "control_door.png",
		["Toggle power"] = "control_power.png",
		["Redecoration"] = "control_redecoration.png",
		["Throttle"] = "control_throttle.png",
		["Flightmode"] = "control_flight.png",
		["H.A.D.S."] = "control_hads.png",
	},
}
TARDIS:AddGUITheme(theme)