local theme = {
	id = "default",
	name = "Default",
	base_id = "base",

	folder = "default",
	frames = {
		subfolder = "frames",
		default = "blue.png",
		on = "green.png",
		off = "red.png",
	},
	backgrounds = {
		subfolder = "backgrounds",
		default = "default.png",
		virtualconsole = "console.jpg",
		main = "default.png",
	},
	text_icons_off = {
		subfolder = "off",
		default = "empty.png",
		["Toggle screens"] = "control_screens.png",
		["Toggle door"] = "control_door.png",
		["Toggle lock"] = "control_lock.png",
		["Toggle power"] = "control_power.png",
		["Self-repair"] = "control_repair.png",
		["Redecoration"] = "control_redecoration.png",
		["Vortex Flight"] = "control_fastremat.png",
		["Throttle"] = "control_throttle.png",
		["Fast Return"] = "control_fastreturn.png",
		["Flightmode"] = "control_flight.png",
		["Anti-Gravs"] = "control_float.png",
		["Physlock"] = "control_physlock.png",
		["H.A.D.S."] = "control_hads.png",

		["Destination"] = "screen_destination.png",
		["Flight Control"] = "screen_thirdperson.png",
		["Console"] = "screen_console.png",
		["Coordinates"] = "screen_coords.png",
		["Music"] = "screen_music.png",
		["Scanner"] = "screen_scanner.png",
		["Settings"] = "screen_settings.png",

		["menu"] = "interface_menu.png",
		["back"] = "interface_back.png",
		["<<<"] = "interface_left.png",
		[">>>"] = "interface_right.png",
		["exit"] = "interface_exit.png",
		["popup"] = "interface_popup.png",
	},
	text_icons_on = {
		subfolder = "on",
		default = "empty.png",
		["Toggle screens"] = "control_screens.png",
		["Toggle door"] = "control_door.png",
		["Toggle lock"] = "control_lock.png",
		["Toggle power"] = "control_power.png",
		["Self-repair"] = "control_repair.png",
		["Redecoration"] = "control_redecoration.png",
		["Vortex Flight"] = "control_fastremat.png",
		["Throttle"] = "control_throttle.png",
		["Flightmode"] = "control_flight.png",
		["Anti-Gravs"] = "control_float.png",
		["Physlock"] = "control_physlock.png",
		["H.A.D.S."] = "control_hads.png",

		["menu"] = "interface_menu.png",
		["back"] = "interface_back.png",
		["<<<"] = "interface_left.png",
		[">>>"] = "interface_right.png",
		["popup"] = "interface_popup.png",
	},
}
TARDIS:AddGUITheme(theme)