local theme = {
	id = "default",
	name = "Default",
	base_id = "base",

	folder = "default",
	frames = {
		subfolder = "frames",
		default = "blue.png",
		on = "green.png",
		off = "red.png",
	},
	backgrounds = {
		subfolder = "backgrounds",
		default = "default.png",
		virtualconsole = "console.jpg",
		main = "default.png",
	},
	text_icons_off = {
		subfolder = "off",
		default = "empty.png",
		toggle_screens = "control_screens.png",
		door = "control_door.png",
		doorlock = "control_lock.png",
		power = "control_power.png",
		repair = "control_repair.png",
		redecorate = "control_redecoration.png",
		vortex_flight = "control_fastremat.png",
		teleport = "control_throttle.png",
		handbrake = "control_handbrake.png",
		engine_release = "control_engine_release.png",
		fastreturn = "control_fastreturn.png",
		flight = "control_flight.png",
		float = "control_float.png",
		physlock = "control_physlock.png",
		hads = "control_hads.png",
		isomorphic = "control_isomorphic.png",
		cloak = "control_cloak.png",

		destination = "screen_destination.png",
		thirdperson = "screen_thirdperson.png",
		virtualconsole = "screen_console.png",
		coordinates = "screen_coords.png",
		music = "screen_music.png",
		scanner = "screen_scanner.png",
		settings = "screen_settings.png",
		["TARDIS Status"] = "screen_status.png",

		menu = "interface_menu.png",
		back = "interface_back.png",
		left_arrow = "interface_left.png",
		right_arrow = "interface_right.png",
		exit = "interface_exit.png",
		popup = "interface_popup.png",
	},
	text_icons_on = {
		subfolder = "on",
		default = "empty.png",
		toggle_screens = "control_screens.png",
		door = "control_door.png",
		doorlock = "control_lock.png",
		power = "control_power.png",
		repair = "control_repair.png",
		redecorate = "control_redecoration.png",
		vortex_flight = "control_fastremat.png",
		teleport = "control_throttle.png",
		handbrake = "control_handbrake.png",
		engine_release = "control_engine_release.png",
		flight = "control_flight.png",
		float = "control_float.png",
		physlock = "control_physlock.png",
		hads = "control_hads.png",
		isomorphic = "control_isomorphic.png",
		cloak = "control_cloak.png",

		menu = "interface_menu.png",
		back = "interface_back.png",
		left_arrow = "interface_left.png",
		right_arrow = "interface_right.png",
		popup = "interface_popup.png",
	},
}
TARDIS:AddGUITheme(theme)