local theme = {
	id = "default-transparent",
	name = "Transparent",
	base_id = "default",

	folder = "default-transparent",
	frames = {
		subfolder = "frames",
		default = "tblue.png",
		on = "tgreen.png",
		off = "tred.png",
	},
	backgrounds = {},
	text_icons_off = {
		subfolder = "off",
		default = "empty.png",
		toggle_screens = "control_screens.png",
		door = "control_door.png",
		power = "control_power.png",
		redecorate = "control_redecoration.png",
		teleport = "control_throttle.png",
		handbrake = "control_handbrake.png",
		engine_release = "control_engine_release.png",
		fastreturn = "control_fastreturn.png",
		flight = "control_flight.png",
		hads = "control_hads.png",
		destination = "screen_destination.png",
		thirdperson = "screen_thirdperson.png",
		coordinates = "screen_coords.png",
		music = "screen_music.png",
		scanner = "screen_scanner.png",
		settings = "screen_settings.png",
		isomorphic = "control_isomorphic.png",
		["TARDIS Status"] = "screen_status.png",
		cloak = "control_cloak.png",
	},
	text_icons_on = {
		subfolder = "on",
		default = "empty.png",
		toggle_screens = "control_screens.png",
		door = "control_door.png",
		power = "control_power.png",
		redecorate = "control_redecoration.png",
		teleport = "control_throttle.png",
		handbrake = "control_handbrake.png",
		engine_release = "control_engine_release.png",
		flight = "control_flight.png",
		hads = "control_hads.png",
		isomorphic = "control_isomorphic.png",
		cloak = "control_cloak.png",
	},
}
TARDIS:AddGUITheme(theme)