local theme = {
    id = "base",
    name = "TextOnly",
    base_id = nil,
    bgcolor = Color(1,1,1,150),

    folder = "base",
    frames = {
        subfolder = nil,
        default = "frame.png",
        on = "frame_on.png",
        off = "frame_off.png",
    },
    backgrounds = {
        subfolder = nil,
        default = "background.png",
        -- virtualconsole = "",
        -- main = "",
        -- coordinates = "",
        -- music = "",
        -- companions = "",
    },
    text_icons_off = {
        subfolder = nil,
        default = "empty.png",
        -- toggle_screens = "",
        -- door = "",
        -- doorlock = "",
        -- power = "",
        -- repair = "",
        -- redecorate = "",
        -- vortex_flight = "",
        -- teleport = "",
        -- fastreturn = "",
        -- flight = "",
        -- float = "",
        -- physlock = "",
        -- hads = "",
        -- destination = "",
        -- thirdperson = "",
        -- virtualconsole = "",
        -- coordinates = "",
        -- music = "",
        -- scanner = "",
        -- settings = "",
        -- menu = "",
        -- back = "",
        -- left_arrow = "",
        -- right_arrow = "",
        -- exit = "",
        -- popup = "",
    },
    text_icons_on = {
        subfolder = nil,
        default = "empty.png",
        -- toggle_screens = "",
        -- door = "",
        -- doorlock = "",
        -- power = "",
        -- repair = "",
        -- redecorate = "",
        -- vortex_flight = "",
        -- teleport = "",
        -- fastreturn = "",
        -- flight = "",
        -- float = "",
        -- physlock = "",
        -- hads = "",
        -- destination = "",
        -- thirdperson = "",
        -- virtualconsole = "",
        -- coordinates = "",
        -- music = "",
        -- scanner = "",
        -- settings = "",
        -- menu = "",
        -- back = "",
        -- left_arrow = "",
        -- right_arrow = "",
        -- exit = "",
        -- popup = "",
    },
}

TARDIS:AddGUITheme(theme)