local theme = {
	id = "base",
	name = "Text only",
	base_id = nil,

	folder = "base",
	frames = {
		subfolder = nil,
		default = "frame.png",
		on = "frame_on.png",
		off = "frame_off.png",
	},
	backgrounds = {
		subfolder = nil,
		default = "background.png",
		-- virtualconsole = "",
		-- main = "",
	},
	text_icons_off = {
		subfolder = nil,
		default = "empty.png",
		-- toggle_screens = "",
		-- door = "",
		-- doorlock = "",
		-- power = "",
		-- repair = "",
		-- redecorate = "",
		-- vortex_flight = "",
		-- teleport = "",
		-- fastreturn = "",
		-- flight = "",
		-- float = "",
		-- physlock = "",
		-- hads = "",
		-- destination = "",
		-- thirdperson = "",
		-- virtualconsole = "",
		-- coordinates = "",
		-- music = "",
		-- scanner = "",
		-- settings = "",
		-- menu = "",
		-- back = "",
		-- left_arrow = "",
		-- right_arrow = "",
		-- exit = "",
		-- popup = "",
	},
	text_icons_on = {
		subfolder = nil,
		default = "empty.png",
		-- toggle_screens = "",
		-- door = "",
		-- doorlock = "",
		-- power = "",
		-- repair = "",
		-- redecorate = "",
		-- vortex_flight = "",
		-- teleport = "",
		-- fastreturn = "",
		-- flight = "",
		-- float = "",
		-- physlock = "",
		-- hads = "",
		-- destination = "",
		-- thirdperson = "",
		-- virtualconsole = "",
		-- coordinates = "",
		-- music = "",
		-- scanner = "",
		-- settings = "",
		-- menu = "",
		-- back = "",
		-- left_arrow = "",
		-- right_arrow = "",
		-- exit = "",
		-- popup = "",
	},
}

TARDIS:AddGUITheme(theme)