name: Generate Hook Types

on:
  push:
    branches:
    - main
    paths:
    - lua/**
    - scripts/generate-hook-types.ps1
    - scripts/bootstrap.ps1
    - scripts/install-tools.ps1
    - .github/workflows/generate-hook-types.yml

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate_hook_types:
    name: Generate Hook Types
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          path: TARDIS
          token: ${{ secrets.TOKEN }}

      - name: Checkout Doors
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          repository: AmyJeanes/Doors
          ref: main
          path: Doors

      - name: Checkout world-portals
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          repository: AmyJeanes/world-portals
          ref: main
          path: world-portals

      - name: Checkout gmod-addon-tools
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          repository: AmyJeanes/gmod-addon-tools
          # renovate: datasource=github-tags depName=AmyJeanes/gmod-addon-tools
          ref: v0.33.3
          path: gmod-addon-tools

      - name: Install tooling
        working-directory: TARDIS
        run: ./scripts/install-tools.ps1
        shell: pwsh

      - name: Generate hook types
        working-directory: TARDIS
        run: ./scripts/generate-hook-types.ps1
        shell: pwsh

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        with:
          repository: TARDIS
          commit_message: "Update generated hook type catalogue"
